import os
os.environ.setdefault("ENGINE_HEADLESS_AUDIO", "1")

import engine_factory

def main():
    engine = engine_factory.boxer_4_crossplane_custom([1, 1, 0, 0])
    # Generate a small audio buffer to validate core DSP path
    buf = engine.gen_audio(1024)
    try:
        import numpy as np
    except Exception:
        np = None
    if np is not None and isinstance(buf, np.ndarray):
        print("Generated ndarray:", buf.shape, buf.dtype)
        b = (buf.astype('<i2') if buf.dtype != '<i2' else buf).tobytes()
        print("As bytes:", len(b), "bytes")
    else:
        print("Generated bytes:", len(buf))

if __name__ == '__main__':
    main()
